name: 'kirick13/workflow-notify-action'
description: 'Sends notification about action results to Discord / Telegram.'

inputs:
  result:
    description: 'Just pass here "toJSON(needs)"'
    required: true
  icon:
    description: 'URL to icon to show in the message (Discord only).'
  signature:
    description: 'Signature of the author of the message (Discord only).'
  discord-webhook:
    description: 'Discord: Webhook URL.'
  # telegram-bot-token:
  #   description: 'Telegram: Bot token.'
  # telegram-chat-id:
  #   description: 'Telegram: Chat ID to send message to.'

runs:
  using: "composite"
  steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.2.0

    - name: Parse result
      shell: bash
      run: bun run $GITHUB_ACTION_PATH/parse.js
      id: data

    # - name: Notify Telegram
    #   shell: bash
    #   run: bun run $GITHUB_ACTION_PATH/send-telegram.js
    #   env:
    #     DATA: ${{ steps.data.outputs.value }}
    #     SIGNATURE: ${{ inputs.signature }}
    #     TELEGRAM_CHAT_ID: ${{ inputs.telegram-chat-id }}
    #     TELEGRAM_BOT_TOKEN: ${{ inputs.telegram-bot-token }}

    - name: Notify Discord
      if: ${{ steps.data.outputs.value != '' && inputs.discord-webhook != '' }}
      shell: bash
      run: bun run $GITHUB_ACTION_PATH/send-discord.js
      env:
        DATA: ${{ steps.data.outputs.value }}
